http://www.abs-cbn.com,,,none
http://abskenticocms.blob.core.windows.net,,,none
http://cdn.innity.net,cdn.innity.net.edgekey.net.,Akamai,cname
http://azuretv2devewu00sca63.blob.core.windows.net,,,none
http://push.abs-cbn.com,,,none
http://sa.kapamilya.com,,,none
http://placehold.it,,,none
http://avd.innity.net,avd.innity.net.edgekey.net.,Akamai,cname
http://entmagandangbuhay.blob.core.windows.net,,,none
http://entmain.blob.core.windows.net,,,none
http://widget.crowdynews.com,www.crowdynews.com.edgekey.net.,Akamai,cname
http://entlangitlupa.blob.core.windows.net,,,none
http://assets.abs-cbn.com,,,none
http://use.typekit.net,use.typekit.net.edgekey.net.,Akamai,cname
http://www.abs-cbn.com/tv/home,,,none
http://www.abs-cbn.com/tv/show,,,none
http://www.abs-cbn.com/tv/shows/asap/main,,,none
http://www.abs-cbn.com/tv/shows/ggv/main,,,none
http://www.abs-cbn.com/tv/shows/angprobinsyano/main,,,none
http://www.abs-cbn.com/tv/shows/wildflower/main,,,none
http://www.abs-cbn.com/tv/shows/alovetolast/main,,,none
http://www.abs-cbn.com/tv/shows/magandangbuhay/main,,,none
http://www.abs-cbn.com/tv/schedule,,,none
