http://www.alibaba.com,,,none
http://u.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://gtms01.alicdn.com,,Alibaba,cname
http://i.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://g.alicdn.com,,Alibaba,cname
http://www.alibaba.com/,,,none
http://www.alibaba.com/new_user_guide_2015.html?tracelog=2015new_home,,,none
http://atms02.alicdn.com,,Alibaba,cname
http://api.video.taobao.com,sh.wagbridge.video.taobao.com.,Alibaba,cname
http://img.alicdn.com,,Alibaba,cname
http://www.alibaba.com/Machinery_p43?nc=y,,,none
http://sc01.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://sc02.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://www.alibaba.com/Mechanical-Parts-Fabrication-Services_p41?nc=y,,,none
http://www.alibaba.com/Tools_p1420?nc=y,,,none
http://www.alibaba.com/Hardware_p42?nc=y,,,none
http://www.alibaba.com/Hand-Tools_pid142003,,,none
http://www.alibaba.com/Garden-Tools_pid12503,,,none
http://www.alibaba.com/Power-Tools_pid1417,,,none
