http://www.aliexpress.com,,,none
http://ae01.alicdn.com,eu1111.alicdn.com.edgekey.net.,Akamai,cname
http://i.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://aeu.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://www.aliexpress.com/buyerprotection/index.html,,,none
http://u.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://is.alicdn.com,wildcard.alicdn.com.edgekey.net.,Akamai,cname
http://www.aliexpress.com/help/newContactUs.htm,,,none
http://www.aliexpress.com/,,,none
http://www.aliexpress.com/all-wholesale-products.html,,,none
http://www.aliexpress.com/category/100003109/women-clothing-accessories.html,,,none
http://us.ynuf.alipay.com,,,none
http://www.aliexpress.com/category/100003070/men-clothing-accessories.html,,,none
http://www.aliexpress.com/category/509/phones-telecommunications.html,,,none
http://www.aliexpress.com/category/7/computer-office.html,,,none
http://www.aliexpress.com/category/44/consumer-electronics.html,,,none
