http://www.amazonaws.com,,,none
http://amazonwebservices.d2.sc.omtrdc.net,,,none
http://a0.awsstatic.com,,,none
http://d0.awsstatic.com,,,none
http://www.amazonaws.com/mp/bi/?nc2=h_l3_bh,,,none
http://www.amazonaws.com/mp/mobile/?nc2=h_l3_d,,,none
http://www.amazonaws.com/mp/storage/?nc2=h_l2_n,,,none
http://www.amazonaws.com/mp/database/?nc2=h_l3_db,,,none
http://www.amazonaws.com/mp/networking/?nc2=h_l3_s,,,none
http://www.amazonaws.com/mp/appdev/?nc2=h_l3_dm,,,none
http://www.amazonaws.com/mp/security/?nc2=h_l3_s,,,none
http://www.amazonaws.com/mp/bi/?nc2=h_l2_al,,,none
http://www.amazonaws.com/mp/mobile/?nc2=h_l3_ms,,,none
