http://www.avito.ru,,,none
http://static.criteo.net,,,none
http://www.tns-counter.ru,,,none
http://www.avito.ru,,,none
http://www.avito.st,,,none
http://mc.yandex.ru,,,none
http://www.avito.ru/profile,,,none
http://www.avito.ru/registration,,,none
http://www.avito.ru/profile/messenger,,,none
http://www.avito.ru/account,,,none
http://www.avito.ru/profile/shop,,,none
http://www.avito.ru/profile/context,,,none
http://www.avito.ru/reklama/delivery#buyer,,,none
http://www.avito.ru/profile/settings,,,none
http://www.avito.ru/additem,,,none
