http://www.bankofamerica.com,,,none
http://www2.bac-assets.com,,,none
http://secure.bankofamerica.com,,,none
http://www.bankofamerica.com/,,,none
http://www.bankofamerica.com/smallbusiness/,,,none
https://www.bankofamerica.com,,,none
http://www.bankofamerica.com/contactus/contactus.go,,,none
http://www.bankofamerica.com/help/overview.go,,,none
http://www.bankofamerica.com/onlinebanking/online-banking-security-faqs.go,,,none
http://www.bankofamerica.com,,,none
