http://www.bbc.com,,,none
http://sa.bbc.co.uk,,,none
http://ssc.api.bbc.com,,,none
http://static.bbc.co.uk,,,none
http://static.bbci.co.uk,,,none
http://ichef.bbci.co.uk,,,none
http://www.bbc.com/,,,none
http://www.bbc.com/accessibility/,,,none
http://www.bbc.co.uk,,,none
http://node1.bbcimg.co.uk,,,none
http://www.bbc.com,,,none
http://www.bbc.com/news/,,,none
http://m.files.bbci.co.uk,m.files.bbci.co.uk.edgekey.net.,Akamai,cname
http://www.bbc.com/sport/,,,none
http://www.bbc.com/weather/,,,none
http://emp.bbci.co.uk,emp.bbci.co.uk.edgekey.net.,Akamai,cname
http://www.bbc.com/earth/,,,none
http://static.bbcverticals.com,,,none
http://www.bbc.com,,,none
http://www.bbc.com/travel/,,,none
http://www.bbc.com/capital/,,,none
