http://www.buzzfeed.com,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://img.buzzfeed.com,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://www.buzzfeed.com/,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://www.buzzfeed.com/news,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://tags.crwdcntrl.net,cs84.wac.edgecastcdn.net.,Edgecast,cname
http://webappstatic.buzzfeed.com,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://analytics.twitter.com,,,none
http://t.co,,,none
http://www.buzzfeed.com/videos,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://videoapp-assets-ak.buzzfeed.com,prod.buzzfeed.map.fastly.net.,Fastly,cname
http://obiwan-static.buzzfeed.com,prod.buzzfeed.map.fastly.net.,Fastly,cname
http://www.buzzfeed.com/quizzes,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://www.buzzfeed.com/tasty,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://www.buzzfeed.com/signin,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://www.buzzfeed.com/signup,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://www.buzzfeed.com/post,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
http://www.buzzfeed.com/animals,http2.buzzfeed.map.fastlylb.net.,Fastly,cname
