http://www.cctv.com,,,none
http://r.img.cctvpic.com,,,none
http://p5.img.cctvpic.com,,,none
http://www.cctv.com/index.shtml,,,none
http://cntv.wrating.com,,,none
http://p1.img.cctvpic.com,,,none
http://www.cctv.com,,,none
http://www.cntv.cn,,,none
http://click.wrating.com,,,none
http://www.cctv.com,,,none
http://www.cctv.com/gyys/index.shtml,,,none
http://www.cctv.com/2017/04/19/ARTIo6hNxYmE1vQQrq7Vd28i170419.shtml,,,none
http://news.cntv.cn,,,none
http://www.cctv.com/2017/04/19/ARTITbvvW1bQjqzzVX1oi8CU170419.shtml,,,none
http://www.cctv.com/2017/04/20/ARTIIaHgB2AYGpoNLA29lkwC170420.shtml,,,none
http://www.cctv.com/special/yqlj/yqlj/index.shtml,,,none
http://www.cctv.com/special/zlgy/zlgy/index.shtml,,,none
http://www.cctv.com/,,,none
