http://www.chaturbate.com,,,none
http://ssl-ccstatic.highwebmedia.com,,,none
http://roomimg.stream.highwebmedia.com,,,none
http://cdn.exoticads.com,,,none
http://www.chaturbate.com/,,,none
http://www.chaturbate.com/accounts/register/,,,none
http://www.chaturbate.com/tags/,,,none
http://www.chaturbate.com/tipping/free_tokens/,,,none
http://www.chaturbate.com/auth/login/,,,none
http://www.chaturbate.com,,,none
http://www.chaturbate.com/auth/password_reset/,,,none
http://www.chaturbate.com/female-cams/,,,none
http://www.chaturbate.com/male-cams/,,,none
