http://www.cnn.com,turner-tls.map.fastly.net.,Fastly,cname
http://amplifypixel.outbrain.com,prod.outbrain.map.fastlylb.net.,Fastly,cname
http://i.cdn.turner.com,cdn.turner.com.edgekey.net.,Akamai,cname
http://www.i.cdn.cnn.com,turner-tls.map.fastly.net.,Fastly,cname
http://cdn.optimizely.com,,,none
http://z.cdn.turner.com,cdn.turner.com.edgekey.net.,Akamai,cname
http://native.sharethrough.com,,,none
http://static.chartbeat.com,global.ssl.fastly.net.,Fastly,cname
http://i.cdn.cnn.com,cdn.cnn.com.edgekey.net.,Akamai,cname
http://www.cnn.com/,turner-tls.map.fastly.net.,Fastly,cname
http://www.cnn.com/us,turner-tls.map.fastly.net.,Fastly,cname
http://i2.cdn.cnn.com,cdn.cnn.com.edgekey.net.,Akamai,cname
http://lt-dt-prd-web-assets.s3.amazonaws.com,,,none
http://cdn.comparecards.com,comparecards.ironhorseholding.netdna-cdn.com.,MaxCDN,cname
http://img.bleacherreport.net,f.ssl.global.fastly.net.,Fastly,cname
http://www.cnn.com/world,turner-tls.map.fastly.net.,Fastly,cname
http://www.cnn.com/politics,turner-tls.map.fastly.net.,Fastly,cname
http://www.cnn.com/opinions,turner-tls.map.fastly.net.,Fastly,cname
http://www.cnn.com/health,turner-tls.map.fastly.net.,Fastly,cname
http://www.cnn.com/entertainment,turner-tls.map.fastly.net.,Fastly,cname
http://api-podium.cnnlabs.io,,,none
http://www.cnn.com/style,turner-tls.map.fastly.net.,Fastly,cname
http://cdn.livefyre.com,d83fhchenkrky.cloudfront.net.,Amazon CloudFront,cname
http://www.cnn.com/travel,turner-tls.map.fastly.net.,Fastly,cname
