http://www.detik.com,,,none
http://cnnindonesia.com,,,none
http://online.detik.com,,,none
http://sgcdnstatic.detik.net.id,,,none
http://sgcdn.detik.net.id,,,none
http://sgimage.detik.net.id,,,none
http://newopenx.detik.com,,,none
http://www.detik.com,,,none
http://www.detik.com/,,,none
https://www.detik.com/mostpopular,,,none
http://cdn.detik.net.id,,,none
http://images.detik.com,,,none
http://beta.newopenx.detik.com,,,none
https://www.detik.com/pilkadadki,,,none
http://gomobile.detik.com,,,none
http://www.detik.com,,,none
http://www.detik.com/fokus/,,,none
http://www.detik.com/mostpopular?utm_source=wp%20detikcom&utm_medium=box%20mostpop&utm_campaign=mostpop,,,none
