http://www.ebay.com,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://i3.ebayimg.com,slot5842.ebay.com.edgekey.net.,Akamai,cname
http://i2.ebayimg.com,slot5842.ebay.com.edgekey.net.,Akamai,cname
http://i1.ebayimg.com,slot5842.ebay.com.edgekey.net.,Akamai,cname
http://i.ebayimg.com,slot5842.ebay.com.edgekey.net.,Akamai,cname
http://ir.ebaystatic.com,slot11847.ebay.com.edgekey.net.,Akamai,cname
http://rtm.ebaystatic.com,slot11847.ebay.com.edgekey.net.,Akamai,cname
http://srx.main.ebayrtm.com,,,none
http://www.ebay.com/,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://www.ebay.com/sch/ebayadvsearch,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://rover.ebay.com,,,none
http://www.ebay.com/rpp/mothers-day,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://www.ebay.com/sl/sell,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://include.ebaystatic.com,,,none
http://www.ebay.com/myb/Summary,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://signin.ebay.com,,,none
http://c.paypal.com,c.paypal.com.edgekey.net.,Akamai,cname
http://secureinclude.ebaystatic.com,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://secureir.ebaystatic.com,slot9428.ebay.com.edgekey.net.,Akamai,cname
http://www.ebay.com/myb/BidsOffers,slot9428.ebay.com.edgekey.net.,Akamai,cname
