http://www.globo.com,,,none
http://s.glbimg.com,,,none
http://s3.glbimg.com,,,none
http://www.globo.com,,,none
http://www.globo.com/todos-os-sites.html,,,none
http://s.videos.globo.com,,,none
http://sawpf.com,,,none
http://www.globo.com/,,,none
http://www.globo.com/privacidade.html,,,none
http://www.globo.com/malhacao/,,,none
http://s2.glbimg.com,,,none
http://vitrines.globo.com,,,none
http://www.globo.com/promocoes,,,none
