http://www.imgur.com,prod.imgur.map.fastlylb.net.,Fastly,cname
http://pixel.quantserve.com,,,none
http://i.imgur.com,prod.imgur.map.fastlylb.net.,Fastly,cname
http://s.imgur.com,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/hot/viral,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/new/viral,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/t/Funny,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/t/The_More_You_Know,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/t/Science_and_Tech,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/t/Gaming,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/t/Eat_What_You_Want,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/t/Aww,prod.imgur.map.fastlylb.net.,Fastly,cname
http://www.imgur.com/t/Inspiring,prod.imgur.map.fastlylb.net.,Fastly,cname
