http://www.indiatimes.com,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://media.indiatimes.in,media.indiatimes.in.edgekey.net.,Akamai,cname
http://ade.clmbtech.com,ade.clmbtech.com-v1.edgekey.net.,Akamai,cname
http://static.clmbtech.com,static.clmbtech.com-v1.edgekey.net.,Akamai,cname
http://images.taboola.com,f2.shared.global.fastly.net.,Fastly,cname
http://staticresources.indiatimes.in,staticresources.indiatimes.in.edgesuite.net.,Akamai,cname
http://www.indiatimes.com/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com/news/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com/technology/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com/lifestyle/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com/entertainment/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com/health/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com/sports/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
http://www.indiatimes.com/videocafe/,www.indiatimes.com-v2.edgekey.net.,Akamai,cname
