http://www.linkedin.com,,,none
http://static.licdn.com,,,none
http://static.licdn.com:443,,,none
https://www.linkedin.com/uas/request-password-reset?trk=uno-reg-guest-home-forgot-password,,,none
http://www.linkedin.com,,,none
https://www.linkedin.com/legal/user-agreement,,,none
https://www.linkedin.com/legal/privacy-policy,,,none
https://www.linkedin.com/legal/cookie-policy,,,none
https://www.linkedin.com/directory/people-a/,,,none
https://www.linkedin.com/directory/people-b/,,,none
https://www.linkedin.com/directory/people-c/,,,none
https://www.linkedin.com/directory/people-d/,,,none
