http://www.microsoft.com,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
http://c.s-microsoft.com,,,none
http://mem.gfx.ms,,,none
http://c.microsoft.com,c.microsoft.com.edgekey.net.,Akamai,cname
http://assets.onestore.ms,,,none
http://ajax.aspnetcdn.com,mscomajax.vo.msecnd.net.,Microsoft Azure,cname
https://www.microsoft.com,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
https://www.microsoft.com/en-us/store/apps/windows?icid=en_US_Store_UH_apps_Win,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
http://web.vortex.data.microsoft.com:443,,,none
http://store-images.s-microsoft.com,,,none
http://statics-onestore-eus-ms-com.akamaized.net,a1843.b.akamai.net.,Akamai,cname
https://www.microsoft.com/en-us/store/apps/windows-phone?icid=en_US_Store_UH_apps_WinPho,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
https://www.microsoft.com/en-us/store/games/windows?icid=en_US_Store_UH_games_Win,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
https://www.microsoft.com/en-us/store/games/windows-phone?icid=en_US_Store_UH_games_WinPho,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
https://www.microsoft.com/en-us/store/movies-and-tv?icid=en_US_Store_UH_ent_MovTV,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
http://video.microsoft.com,,,none
http://musicimage.xboxlive.com,,,none
http://m.s-microsoft.com,,,none
https://www.microsoft.com/en-us/store/music?icid=en_US_Store_UH_ent_Music,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
http://www.microsoft.com,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
https://www.microsoft.com/en-us/store/gift-cards,www.microsoft.com-c-2.edgekey.net.,Akamai,cname
http://web.vortex.data.microsoft.com,,,none
http://cdn.optimizely.com,,,none
http://compass.xboxlive.com,compass.xboxlive.com-c.edgesuite.net.,Akamai,cname
http://compass-ssl.microsoft.com,,,none
