http://www.msn.com,,,none
http://img-s-msn-com.akamaized.net,a1834.dspg2.akamai.net.,Akamai,cname
http://static-hp-eus-s-msn-com.akamaized.net,a1075.g2.akamai.net.,Akamai,cname
http://c.msn.com,,,none
http://otf.msn.com,,,none
http://www.msn.com/en-us,,,none
http://www.msn.com/en-us/news,,,none
http://static-entertainment-eus-s-msn-com.akamaized.net,a1505.g2.akamai.net.,Akamai,cname
http://static-hp-eus.s-msn.com,static.s-msn.com.edgekey.net.,Akamai,cname
http://www.msn.com/en-us/weather,,,none
http://static-weather-eus-s-msn-com.akamaized.net,a1082.g2.akamai.net.,Akamai,cname
http://www.msn.com/en-us/entertainment,,,none
http://www.msn.com/en-us/sports,,,none
http://static-sports-eus-s-msn-com.akamaized.net,a1189.g2.akamai.net.,Akamai,cname
http://www.msn.com/en-us/money,,,none
http://static-finance-eus-s-msn-com.akamaized.net,a1694.g2.akamai.net.,Akamai,cname
http://www.msn.com/en-us/lifestyle,,,none
http://www.msn.com/en-us/health,,,none
