http://www.paypal.com,,,none
http://www.paypalobjects.com,,,none
http://t.paypal.com,t.paypal.com.edgekey.net.,Akamai,cname
https://www.paypal.com/us/webapps/mpp/home,,,none
https://www.paypal.com/us/webapps/mpp/getting-started/get-account/overview,,,none
https://www.paypal.com/us/webapps/mpp/pay-online,,,none
https://www.paypal.com/us/webapps/mpp/paypal-credit,,,none
https://www.paypal.com/us/webapps/mpp/pay-in-stores,,,none
https://www.paypal.com/us/webapps/mpp/pay-on-ebay,,,none
https://www.paypal.com/us/webapps/mpp/about-paypal-products,,,none
https://www.paypal.com/us/webapps/mpp/merchant,,,none
