http://www.pinterest.com,,,none
http://s.pinimg.com,,,none
http://s-media-cache-ak0.pinimg.com,,,none
http://www.pinterest.com/_/_/about/terms-service/,,,none
http://cdnjs.cloudflare.com,,Cloudflare,name
http://about.pinterest.com,prod.pinterest.global.map.fastly.net.,Fastly,cname
http://assets.pinterest.com,assets.pinterest.com.edgekey.net.,Akamai,cname
http://www.pinterest.com/_/_/about/privacy/plain.html,,,none
http://www.pinterest.com/_/_/about/,,,none
http://www.pinterest.com/_/_/blog/,,,none
http://blog.pinterest.com,prod.pinterest.global.map.fastly.net.,Fastly,cname
http://www.pinterest.com/_/_/business/,,,none
http://www.pinterest.com/_/_/about/privacy/,,,none
http://www.pinterest.com/_/_/help/?utm_campaign=signup_page&utm_source=web,,,none
http://help.pinterest.com,prod.pinterest.global.map.fastly.net.,Fastly,cname
http://www.pinterest.com/ios/,,,none
http://www.pinterest.com/android/,,,none
