http://www.sogou.com,,,none
http://dl.web.sogoucdn.com,,,none
http://account.sogou.com,,,none
http://www.sogou.com/docs/more.htm?v=1,,,none
http://www.sogou.com,,,none
http://logo.www.sogou.com,,,none
http://www.sogou.com/docs/terms.htm?v=1,,,none
http://js.sogou.com,,,none
http://www.sogou.com/,,,none
http://www.sogou.com/labs/,,,none
http://www.sogou.com/docs/help/helpbox.htm?v=1,,,none
http://www.sogou.com/pinyin,,,none
http://img01.sogoucdn.com,,,none
http://pinyin.sogou.com,,,none
http://dl.pinyin.sogou.com,,,none
http://img02.sogoucdn.com,,,none
http://img04.sogoucdn.com,,,none
http://img03.sogoucdn.com,,,none
http://s11.cnzz.com,,,none
http://www.sogou.com,,,none
http://www.sogou.com/docs/about.htm?v=1,,,none
http://www.sogou.com/docs/home.htm?v=1,,,none
http://fuwu.sogou.com,,,none
