http://www.stackexchange.com,,,none
http://www.gravatar.com,,,none
http://cdn.sstatic.net,,,none
http://i.stack.imgur.com,,,none
http://www.stackexchange.com/tour,,,none
http://www.stackexchange.com/about,,,none
http://www.stackexchange.com/sites,,,none
http://meta.stackexchange.com,,,none
http://www.stackexchange.com/leagues,,,none
http://www.stackexchange.com/newsletters,,,none
http://www.stackexchange.com/blogs,,,none
http://www.stackexchange.com/,,,none
http://www.stackexchange.com/questions?tab=realtime,,,none
http://www.stackexchange.com?pagesize=15,,,none
