http://www.tumblr.com,,,none
http://px.srvcs.tumblr.com,,,none
http://assets.tumblr.com,,,none
http://tumblr.com,,,none
http://68.media.tumblr.com,,,none
http://cookiex.ngd.yahoo.com,,,none
http://www.tumblr.com/,,,none
http://www.tumblr.com/policy/,,,none
http://www.tumblr.com/forgot_password,,,none
https://www.tumblr.com/policy,,,none
https://www.tumblr.com/privacy_policy,,,none
https://www.tumblr.com/jobs,,,none
https://www.tumblr.com/login,,,none
https://www.tumblr.com/register,,,none
http://www.tumblr.com/support,,,none
