http://www.txxx.com,,,none
http://static5.tubecup.org,,,none
http://static6.tubecup.org,,,none
http://ipornia.com,,,none
http://static4.tubecup.org,,,none
http://cdn1ht.traffichaus.com,traffichauscdn.0x912k.netdna-cdn.com.,MaxCDN,cname
http://www.txxx.com,,,none
http://txxx-tn1.yurivideo.com,,,none
http://www.txxx.com,,,none
http://www.txxx.com/login/?action=not_allowed,,,none
http://ads.adamoads.com,,,none
http://www.txxx.com/login.php,,,none
http://www.txxx.com/signup.php,,,none
http://www.txxx.com/,,,none
http://www.txxx.com/latest-updates/,,,none
http://www.txxx.com/top-rated/,,,none
http://www.txxx.com/most-popular/,,,none
http://www.txxx.com/longest/,,,none
