http://www.upornia.com,,,none
http://static2.upornia.org,,,none
http://static1.upornia.org,,,none
http://script.bangdom.com,,,none
http://cdn1ht.traffichaus.com,traffichauscdn.0x912k.netdna-cdn.com.,MaxCDN,cname
http://syndication.exoclick.com,,,none
http://static.upornia.com,,,none
http://static3.upornia.org,,,none
http://js.bulkhentai.com,,,none
http://upornia.com,,,none
http://www.upornia.com,,,none
http://www.upornia.com/watch-later/,,,none
http://www.upornia.com/history/,,,none
http://www.upornia.com/most-popular/,,,none
http://www.upornia.com/videos/487098/mom-looks-so-hot-in-her-nylons/,,,none
http://s7.addthis.com,,,none
http://www.upornia.com/videos/345566/gmmg0000/,,,none
http://www.upornia.com/videos/375503/my-mother-came-into-my-room-suddenly/,,,none
http://www.upornia.com/videos/193568/mother-i-d-like-to-fuck-60-pov/,,,none
