http://www.vimeo.com,,,none
http://f.vimeocdn.com,prod.vimeo-video.map.fastly.net.,Fastly,cname
http://www.vimeo.com/upload,,,none
http://cdn.optimizely.com,,,none
http://www.vimeo.com,,,none
http://www.vimeo.com/about,,,none
http://player.vimeo.com,,,none
http://secure.gravatar.com,,,none
http://i.vimeocdn.com,prod.vimeo-video.map.fastly.net.,Fastly,cname
http://www.vimeo.com/blog,,,none
http://www.vimeo.com/help/guidelines,,,none
http://www.vimeo.com/jobs,,,none
http://www.vimeo.com/help,,,none
http://cdn.statuspage.io,g.global-ssl.fastly.net.,Fastly,cname
http://vimeo.zendesk.com,,,none
http://s3-us-west-2.amazonaws.com,,,none
http://zendesk.tv,,,none
http://p9.zdassets.com,,,none
http://www.vimeo.com/videoschool,,,none
http://www.vimeo.com/help/faq,,,none
