http://www.walmart.com,www.walmart.com.edgekey.net.,Akamai,cname
http://b.wal.co,b.wal.co.edgekey.net.,Akamai,cname
http://a14.wal.co,a.wal.co.edgekey.net.,Akamai,cname
http://i5.walmartimages.com,walmartgc.hs.llnwd.net.,Limelight,cname
http://www.walmart.com/account/login,www.walmart.com.edgekey.net.,Akamai,cname
http://ll-us-i5.wal.co,walmartgc-1.hs.llnwd.net.,Limelight,cname
http://www.walmart.com/cp/free-shipping/1088989,www.walmart.com.edgekey.net.,Akamai,cname
http://beacon.walmart.com,beacon.walmart.com.akadns.net.,Akamai,cname
https://www.walmart.com/all-departments,www.walmart.com.edgekey.net.,Akamai,cname
http://www.walmart.com/store,www.walmart.com.edgekey.net.,Akamai,cname
http://6e58e2e225bb143c019e-e234a4d870c026b5f56b4446f6e62d64.ssl.cf1.rackcdn.com,cf1.rackcdn.com.edgekey.net.,Akamai,cname
http://f.wishabi.net,d.global-ssl.fastly.net.,Fastly,cname
http://cdn.cpnscdn.com,cpnscdn.com.edgekey.net.,Akamai,cname
http://www.walmart.com/browse/0/0?cat_id=0&facet=pickup_and_delivery:FREE%20Pickup%20Today,www.walmart.com.edgekey.net.,Akamai,cname
http://www.walmart.com/cp/ideas/8932632,www.walmart.com.edgekey.net.,Akamai,cname
http://www.walmart.com/account/,www.walmart.com.edgekey.net.,Akamai,cname
http://www.walmart.com/cp/Gift-Cards/96894?povid=96894+%7C+contentZone2+%7C+2015-06-03+%7C+1+%7C+LN-Shop+Gift+Card+Global+Nav,www.walmart.com.edgekey.net.,Akamai,cname
http://fonts.walmart.com,fonts.walmart.com.edgekey.net.,Akamai,cname
