http://www.weebly.com,,,none
http://cdn2.editmysite.com,weebly.map.fastly.net.,Fastly,cname
http://use.typekit.net,use.typekit.net.edgekey.net.,Akamai,cname
http://pixel.quantserve.com,akamai-pixel.quantserve.com.akadns.net.,Akamai,cname
http://www.weebly.com/features,,,none
http://code.jquery.com,code.jquery.netdna-cdn.com.,MaxCDN,cname
http://www.weebly.com/themes,,,none
http://cdn1.editmysite.com,weebly.map.fastly.net.,Fastly,cname
http://www.weebly.com/pricing,,,none
http://www.weebly.com/,,,none
http://www.weebly.com?lang=da,,,none
http://www.weebly.com?lang=de,,,none
http://www.weebly.com?lang=es,,,none
http://www.weebly.com?lang=fr,,,none
http://www.weebly.com?lang=it,,,none
