http://www.wikia.com,,,none
http://fandom.wikia.com,,,none
http://pixel.quantserve.com,,,none
https://www.wikia.com/signin,,,none
https://www.wikia.com/register,,,none
http://www.wikia.com/Special:CreateNewWiki,,,none
http://slot1.images3.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://slot1.images1.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://slot1.images.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://slot1.images2.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://www.wikia.com,,,none
http://a.wikia-beacon.com,,,none
http://slot1.images4.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://www.wikia.com/join,,,none
http://www.wikia.com/wiki/Special:UserLogout?returnto=,,,none
http://www.wikia.com/explore,,,none
http://vignette.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://www.wikia.com/WAM,,,none
http://static.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://vignette4.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://vignette3.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://vignette2.wikia.nocookie.net,wikia.nocookie.net.,Fastly,cname
http://www.wikia.com,,,none
http://www.wikia.com/signin,,,none
