http://www.wittyfeed.com,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.audienceinsights.net,,,none
http://cdn.wittyfeed.com,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/news,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://platform.instagram.com,,,none
http://platform.twitter.com,cs472.wac.edgecastcdn.net.,Edgecast,cname
http://www.wittyfeed.com/inspiration,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/celebrities,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/animals,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/bizarre,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/diy,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/health-fitness,www.wittyfeed.com.edgekey.net.,Akamai,cname
http://www.wittyfeed.com/history-culture,www.wittyfeed.com.edgekey.net.,Akamai,cname
