http://www.xvideos.com,,,none
http://static-hw.xvideos.com,cds.q8q4g4t6.hwcdn.net.,Highwinds,cname
http://www.xvideos.com/switch-theme,,,none
http://www.xvideos.com,,,none
http://www.xvideos.com/rss/rss.xml,,,none
http://www.xvideos.com/,,,none
http://www.xvideos.com/porn,,,none
http://www.xvideos.com/pornstars,,,none
http://www.xvideos.com/channels,,,none
http://www.xvideos.com/verified/videos,,,none
http://www.xvideos.com/profileslist,,,none
http://img-hw.xvideos.com,cds.g9c9c3d5.hwcdn.net.,Highwinds,cname
http://img-egc.xvideos.com,cs235.wpc.systemcdn.net.,Edgecast,cname
