http://www.yahoo.com,,,none
http://beap-bc.yahoo.com,,,none
http://s.yimg.com,,,none
https://www.yahoo.com/,,,none
https://www.yahoo.com/everything/,,,none
http://www.yahoo.com,,,none
https://www.yahoo.com/news/politics/,,,none
https://www.yahoo.com/celebrity/,,,none
https://www.yahoo.com/movies/,,,none
https://www.yahoo.com/music/,,,none
https://www.yahoo.com/tv/,,,none
https://www.yahoo.com/style/,,,none
https://www.yahoo.com/beauty/,,,none
